todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('todo_list.urls')),
    path('admin/', admin.site.urls),
]

todo/todo_list/urls.py
""" URLs configuration of todo app """
from django.urls import path
from . import views

app_name = 'todo_list'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<int:list_id>/', views.delete, name='delete'),
    path('cross_of/<int:list_id>/', views.cross_off, name='cross_off'),
    path('uncross/<int:list_id>/', views.uncross, name='uncross'),
    path('edit/<int:list_id>/', views.edit, name='edit')
    ]

todo/todo_list/models.py
""" Models of todo app """
from django.db import models

class List(models.Model):
    """ List model of todo app """
    item = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.item} | {str(self.completed)}'

todo/todo_list/forms.py
""" Form to control objects in todo app """
from django import forms
from .models import List

class ListForm(forms.ModelForm):
    """ ModelForm of List Model! """
    class Meta:
        model = List
        fields = ['item', 'completed']

todo/todo_list/views.py
""" Views of todo app """
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import List
from .forms import ListForm

def index(request):
    """ Index view for todo app """
    if request.method == "POST":
        form = ListForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, "Item Has Been Added To List!")

    template = 'todo_list/index.html'
    all_items = List.objects.order_by('completed')
    context = {
        'all_items': all_items,
    }
    return render(request, template, context)

def cross_off(request, list_id):
    """ Action for completed tasks """
    item = List.objects.get(pk=list_id)
    item.completed = True
    item.save()
    return redirect('todo_list:index')

def uncross(request, list_id):
    """ Action to uncross the crossed items! """
    item = List.objects.get(pk=list_id)
    item.completed = False
    item.save()
    return redirect('todo_list:index')

def delete(request, list_id):
    """ View to delete items of todo """
    item = List.objects.get(pk=list_id)
    item.delete()
    messages.success(request, "Item Has Been Deleted!")
    return redirect('todo_list:index')

def edit(request, list_id):
    """ Update the choosen item """
    template = 'todo_list/edit.html'
    item = List.objects.get(pk=list_id)
    context = {
        'item': item,
    }
    if request.method == "POST":
        form = ListForm(request.POST or None, instance=item)
        if form.is_valid():
            form.save()
            messages.success(request, "Item Has Been Edited")
            return redirect("todo_list:index")
    else:
        return render(request, template, context)

todo/todo_list/templates/todo_list/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'todo_list/css/bootstrap.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'todo_list/css/main.css' %}">
    <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        <!-- Include the navbar -->
        {% include 'todo_list/navbar.html' %}
        <br>
        <!-- Main content of todo app -->
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'todo_list/js/jquery-3.4.1.slim.min.js' %}" ></script>
        <script src="{% static 'todo_list/js/popper.min.js' %}"></script>
        <script src="{% static 'todo_list/js/bootstrap.min.js' %}"></script>
    </body>
</html>

todo/todo_list/templates/todo_list/edit.html
{% extends 'todo_list/base.html' %}

{% block title %}
    To-Do Edit
{% endblock title %}

{% block content %}
    {% if item %}
    <form method="POST" class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        <input type="text" class="form-control mr-sm-2" value="{{ item.item }}" name="item" autocomplete="off">
        <input type="hidden" value="{{ item.completed }}" name="completed">
        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Edit Item</button>
    </form>
    {% endif %}
{% endblock content %}

todo/todo_list/templates/todo_list/index.html
{% extends 'todo_list/base.html' %}
{% load static %}

{% block title %}
    To-Do App
{% endblock title %}

{% block  content %}
    {% if  messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissable" role="alert">
                <button class="close" data-dismiss="alert">
                    <small><sup>x</sup></small>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% if all_items %}
        <table class="table table-bordered">
            {% for todo in all_items %}
                {% if todo.completed %}
                    <tr class="table-secondary">
                        <td class="striker">
                            <a href="{% url 'todo_list:edit' todo.id %}">{{ todo.item }}</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'todo_list:uncross' todo.id %}">Uncross</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'todo_list:delete' todo.id %}" class="">Delete</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td>
                            <a href="{% url 'todo_list:edit' todo.id %}">{{ todo.item }}</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'todo_list:cross_off' todo.id %}">Cross Off</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'todo_list:delete' todo.id %}" class="">Delete</a>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    {% endif %}
{% endblock content %}

todo/todo_list/templates/todo_list/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'todo_list:index' %}">To-Do List</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>
        <form class="form-inline my-2 my-lg-0" method="POST">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="input" placeholder="Add Item" name="item" autocomplete="off">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Add To List</button>
        </form>
    </div>
</nav>